### ISSUE TITLE
Sometimes showing Celsius instead of Fahrenheit

### ISSUE THREAD

**Issue by mikesalz** [PostLogical/ooler#18]
## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1287
Downloaded Repositories | 9

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 1
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 26, 2023 at 3:25 PM
-- | --
current_recorder_run | May 31, 2023 at 5:02 PM
estimated_db_size | 89.72 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

For starters, THANK YOU for creating this integration!  I have been hoping for something like this since we bought our Oolers a couple of years ago.

I just added the integration today.  I read that Water Level and Wattage are still being worked on.  No problem.  I'm especially looking forward to Water Level.  

But I also notice that one of our two Oolers is showing what appears to be Celsius instead of Fahrenheit.  Mike's is good, but Jamie's is not:
![image](https://github.com/PostLogical/ooler/assets/46855061/d4c79bb0-8deb-4c7a-be31-920866372381)

![image](https://github.com/PostLogical/ooler/assets/46855061/22837301-217b-440a-9ea6-bd9a2ae18f85)

Thoughts?

### Reproduction steps

1. I can provide later if needed.
2.
3.
...

### Debug logs

```text
I can provide later if needed.
```

**Comment by PostLogical** [comment]
So glad to see someone is using this code! Sorry I've been busy and didn't yet find a solution to your issue. I'm assuming it either resolved itself or you found a fix. If there's something to be fixed, please do let me know.

**Comment by PostLogical** [comment]
So glad to see someone is using this code! Sorry I've been busy and didn't yet find a solution to your issue. I'm assuming it either resolved itself or you found a fix. If there's something to be fixed, please do let me know.

**Comment by mikesalz** [comment]
Yeah, it was just me being dumb. My wife’s Ooler was set to Celsius and I didn’t realize it :)

I did end up having some other issues. Maybe a Bluetooth thing. But it kept losing the connection to HA and also to the Ooler app. I disabled for now but would love to give it another shot. Can the app and integration not run at the same time? 

Thanks for getting back to me!

**Comment by PostLogical** [comment]
Yeah unfortunately the Bluetooth implementation Ooler uses can only have one connection at a time, so if you're accessing it with the app then home assistant can't connect, and if home assistant is connected, the app can't connect. That's why I created the Bluetooth connection toggle, but it currently tries to reconnect immediately so it is not well done. I click that toggle and immediately open the app and then keep hitting the toggle if that didn't work right away. But I have to force quit the app or otherwise disconnect to give access back to HASS. Open to ideas on how to make this work better.
